package by.epam.hospital.controller;

public enum CommandName {
    AUTHORIZATION,
    FIRST_VISIT,
    SIGN_OUT,
    REGISTER_CLIENT,
    FIND_ROLE_CONTROL_ATTRIBUTES,
    FIND_DEPARTMENT_CONTROL_ATTRIBUTES,
    ROLE_CONTROL,
    CHANGE_DEPARTMENT_HEAD,
    MOVE_DOCTOR_TO_DEPARTMENT
}
